require "k-prelude.k"
require "builtins/list.k"
require "builtins/map.k"
require "builtins/set.k"
require "builtins/mint.k"
require "io/io.k"
//require "modules/substitution.k"
//require "modules/k-functional-visitor.k"

module JS-PRELUDE

imports BUILTIN-HOOKS
imports K
imports LIST
imports MAP
imports SET
imports MINT
imports K-IO
//imports SUBSTITUTION
//imports K-FUNCTIONAL-VISITOR

endmodule
